name: Node CI/CD pipeline

on:
  push:
    branches: [main]

jobs:
  test:
    name: test
    runs-on: arch-latest

    strategy:
      matrix:
        node-version: [21.x]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Setup db
        run:
          rm messager.sqlite
          touch messager.sqlite
          sqlite3 messager.sqlite3 < createMessager.sql
      
      - name: Setup and install npm
        run:
          npm install
          npx tsc
          npm test

      - name: Clean db
        run:
          rm messager.sqlite
